services:
  - type: web
    name: dp-vision-tracer-api
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    autoDeploy: true
